In [2]:
import pandas as pd
url = "https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv"
df = pd.read_csv(url)

df.head()

   customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [4]:
df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors = 'coerce')
print(df['TotalCharges'].isnull().sum())

11

In [5]:
df = df.dropna(subset=['TotalCharges'])
df = df.drop('customerID' , axis=1)

print(df.shape)

(7032, 20)

In [6]:
df_encoded = pd.get_dummies(df, drop_first = True)
df_encoded.head()

   SeniorCitizen  tenure  ...  PaymentMethod_Mailed check  Churn_Yes
0              0       1  ...                       False      False
1              0      34  ...                        True      False
2              0       2  ...                        True       True
3              0      45  ...                       False      False
4              0       2  ...                       False       True

[5 rows x 31 columns]

In [7]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   SeniorCitizen                          7032 non-null   int64
 1   tenure                                 7032 non-null   int64
 2   MonthlyCharges                         7032 non-null   float64
 3   TotalCharges                           7032 non-null   float64
 4   gender_Male                            7032 non-null   bool
 5   Partner_Yes                            7032 non-null   bool
 6   Dependents_Yes                         7032 non-null   bool
 7   PhoneService_Yes                       7032 non-null   bool
 8   MultipleLines_No phone service         7032 non-null   bool
 9   MultipleLines_Yes                      7032 non-null   bool
 10  InternetService_Fiber optic            7032 non-null   bool
 11  InternetService_No                     7032 non-null   bool
 12  OnlineSecurity_No internet service     7032 non-null   bool
 13  OnlineSecurity_Yes                     7032 non-null   bool
 14  OnlineBackup_No internet service       7032 non-null   bool
 15  OnlineBackup_Yes                       7032 non-null   bool
 16  DeviceProtection_No internet service   7032 non-null   bool
 17  DeviceProtection_Yes                   7032 non-null   bool
 18  TechSupport_No internet service        7032 non-null   bool
 19  TechSupport_Yes                        7032 non-null   bool
 20  StreamingTV_No internet service        7032 non-null   bool
 21  StreamingTV_Yes                        7032 non-null   bool
 22  StreamingMovies_No internet service    7032 non-null   bool
 23  StreamingMovies_Yes                    7032 non-null   bool
 24  Contract_One year                      7032 non-null   bool
 25  Contract_Two year                      7032 non-null   bool
 26  PaperlessBilling_Yes                   7032 non-null   bool
 27  PaymentMethod_Credit card (automatic)  7032 non-null   bool
 28  PaymentMethod_Electronic check         7032 non-null   bool
 29  PaymentMethod_Mailed check             7032 non-null   bool
 30  Churn_Yes                              7032 non-null   bool
dtypes: bool(27), float64(2), int64(2)
memory usage: 460.1 KB

In [8]:
from sklearn.model_selection import train_test_split
X = df_encoded.drop(['Churn_Yes'], axis = 1)
y = df_encoded['Churn_Yes']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

print("Traning Data Size (X_train):", X_train.shape)
print("Testing Data Size (X_test):", X_test.shape)

Traning Data Size (X_train): (5625, 30)
Testing Data Size (X_test): (1407, 30)

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
print("Done")

Done

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score

model = LogisticRegression(max_iter=1000, random_state = 42)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy * 100:.2f}%\n")

print("Classification Report:")
print(classification_report(y_test, y_pred))

Model Accuracy: 78.75%

Classification Report:
              precision    recall  f1-score   support

       False       0.83      0.89      0.86      1033
        True       0.62      0.52      0.56       374

    accuracy                           0.79      1407
   macro avg       0.73      0.70      0.71      1407
weighted avg       0.78      0.79      0.78      1407